### PR TITLE
WIP Suspend-to-idle

### PR DESCRIPTION
**Pull request by jloehel**
This pull-request introduces the method s0 and s0k for testing _suspend-to-idle (s2idle)_ [1] and adds a default value for the variable _alternate_.

[1] https://www.kernel.org/doc/html/v4.15/admin-guide/pm/sleep-states.html#suspend-to-idle

### CODE REVIEW

**Comment by sndirsch** [comment]
Looks good! I'm just not sure, whether we want to name suspend-to-idle "S0". Thanks also for initializing the alternate variable. ;-)

**Comment by jloehel** [comment]
I read about the power states here [1] and he names the state Suspend-To-Idle _S0_. But I am not sure about the accurate naming of this state.

[1] https://www.kernel.org/doc/Documentation/power/states.txt

**Comment by sndirsch** [comment]
Ok. Then let's take it as is. Thanks for the pointer!

**Comment by sndirsch** [comment]
Ok. I don't understand github. :-( Reopen ...

**Pull request merged**
